apiVersion: v1
kind: Pod
meta:
  name: insecure-hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
  volumes:
    - name: host-volume
      hostPath:
        path: /