apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8spsphostpath
spec:
  crd:
    spec:
      names:
        kind: K8sPSPHostPath
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8spsphostpath

        violation[{"msg": "HostPath volumes are not allowed"}] {
          input.review.object.spec.volumes[_].hostPath
        }