apiVersion: v1
kind: Pod
meta:
  name: secure-hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: hostpath-volume
          mountPath: /hostpath
  volumes:
    - name: host-volume
      hostPath:
        path: /tmp