apiVersion: v1
kind: Pod
meta:
  name: pod-secure-privileged
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true